### ISSUE TITLE
Edit Noti model & endpoints

### ISSUE THREAD

**Issue by bin315a1** [poolup-devs/poolup_backend#7]
**Current Issue**
Currently, the notification only exists for:
1. When a Rider joins the ride
2. When a Rider cancels the ride

Notifications should cover other edge cases as well:
1. When the Driver cancels the ride
2. Any notification regarding transactions (perhaps a receipt notification)

**TODO**
1. Create notifications when Driver cancels a ride
2. Design and create a notification for transaction notifications

**Potential Conflicts/ Alternatives**
Notification for Transaction notifications would have to wait until Stripe's implementation is complete

**Additional context**

**Comment by bin315a1** [comment]
Work IP

**Comment by bin315a1** [comment]
Ride cancellation notification implemented

**Comment by elin4046** [comment]
**What is currently implemented:** 

- Driver is notified when a new passenger joins a ride. 
- All passengers are notified when the driver cancels the ride. 
- Only the driver is notified of the cancellation when a passenger cancels a ride. 

**Proposed Changes:** 

Joining/Cancelling a Ride 
- _All passengers_ should be notified when a new passenger joins, not just the driver. 
- _All passengers_ should be notified when one passenger cancels a ride, not just the driver. 

Leaving Reviews
- Drivers should receive a notification asking them to leave a review for each passenger after a ride has completed 
   - Definition of completed ride = at least one passenger AND 2 hours after beginning of ride 
- Passengers should receive a notification asking to review the driver once the ride has completed
